-- Samson 0032 — a way off the leaderboard
--
-- Ships BEFORE the view, because a view filtering on a column the database does
-- not have is a broken view — ADR 0016, Consequences.
--
-- WHY the default is false (visible), argued rather than assumed: what the
-- leaderboard exposes is a display name the user typed for other people to read
-- and a score they generated by using the game layer. Nothing observed, nothing
-- inferred. And nobody appears without having volunteered a name at all — a
-- user with no display_name is absent from the view entirely, which is ADR
-- 0016 §3.
--
-- AI-NOTE: the counter-argument is recorded in ADR 0016 §4 rather than settled
--          here. If this app ever has real users rather than a demo cohort,
--          consent-by-default stops being defensible and this default should
--          flip to true. That is one `alter column ... set default` and a
--          paragraph in the ADR; do not treat the current default as settled
--          policy.

alter table public.users
  add column if not exists leaderboard_opt_out boolean not null default false;

comment on column public.users.leaderboard_opt_out is
  'When true, this user is absent from public.leaderboard. See docs/adr/0016-leaderboard.md.';
