/**
 * Executable invariants.
 *
 * WHY: CLAUDE.md states rules in prose, and prose does not survive fifty
 *      commits. These tests are the cheapest thing in phase 0 and the reason
 *      the rules stay true. They need no database, network, or API key.
 */
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { describe, expect, it } from 'vitest';
import { STAGE_MODELS } from '../../src/llm/models';

const ROOT = join(__dirname, '..', '..');
const SEARCH_DIRS = ['src', 'app', 'scripts', 'tests'];
const SKIP_DIRS = new Set(['node_modules', '.next', '.git', 'dist']);

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.has(entry)) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (/\.(ts|tsx)$/.test(entry)) out.push(full);
  }
  return out;
}

// WHY: this file names the very strings it searches for, so it must exclude
//       itself or it always fails. This is the only exemption, and it is here
//       rather than in a list of allowed paths so it cannot quietly grow.
const SELF = 'tests/unit/invariants.test.ts';

// Generated by `supabase gen types`, not hand-written. It legitimately contains
// the llm_calls column names, openrouter_id among them. Also ignored by ESLint
// and Prettier for the same reason.
const GENERATED = 'src/db/types.ts';

function sourceFiles(): { path: string; rel: string; text: string }[] {
  return SEARCH_DIRS.flatMap((dir) => {
    try {
      return walk(join(ROOT, dir));
    } catch {
      return [];
    }
  })
    .map((path) => ({
      path,
      rel: relative(ROOT, path).split(sep).join('/'),
      text: readFileSync(path, 'utf8'),
    }))
    .filter((f) => f.rel !== SELF && f.rel !== GENERATED);
}

describe('CLAUDE.md #2 — all LLM calls go through the gateway', () => {
  // WHY: duplicated from the ESLint rule on purpose. Lint can be silenced with
  //      an inline disable comment; this cannot.
  const isGateway = (rel: string) => rel.startsWith('src/llm/');

  it('names OpenRouter nowhere outside src/llm/', () => {
    const offenders = sourceFiles()
      .filter((f) => !isGateway(f.rel))
      .filter((f) => /openrouter/i.test(f.text))
      .map((f) => f.rel);

    expect(offenders, 'reach OpenRouter through callLLM() instead').toEqual([]);
  });

  it('reads the API key nowhere outside src/llm/', () => {
    const offenders = sourceFiles()
      .filter((f) => !isGateway(f.rel))
      .filter((f) => f.text.includes('OPENROUTER_API_KEY'))
      .map((f) => f.rel);

    expect(offenders).toEqual([]);
  });

  it('exposes exactly one call entry point', () => {
    const gateway = readFileSync(join(ROOT, 'src', 'llm', 'gateway.ts'), 'utf8');
    expect(gateway).toContain('export async function callLLM');
  });
});

describe('CLAUDE.md #10 — the service role key never appears in application code', () => {
  it('is absent from src/ and app/', () => {
    // Scripts and tests may use it for fixture setup; a request path may not.
    const offenders = sourceFiles()
      .filter((f) => f.rel.startsWith('src/') || f.rel.startsWith('app/'))
      .filter((f) => /SERVICE_ROLE|service_role/.test(f.text))
      .map((f) => f.rel);

    expect(offenders).toEqual([]);
  });
});

describe('PLAN.md phase 2 — the critic runs on a different model from the planner', () => {
  it('gives the planner and critic different primary models', () => {
    // WHY: a critic sharing the planner's weights shares its blind spots, and
    //      the safety loop degrades into agreement.
    expect(STAGE_MODELS.planner[0]).not.toBe(STAGE_MODELS.critic[0]);
  });

  it('gives the planner and critic different model families', () => {
    const family = (slug: string) => slug.split('/')[0];
    expect(family(STAGE_MODELS.planner[0]!)).not.toBe(family(STAGE_MODELS.critic[0]!));
  });

  it('gives every stage at least one model', () => {
    for (const [stage, models] of Object.entries(STAGE_MODELS)) {
      expect(models.length, `${stage} has no model configured`).toBeGreaterThan(0);
    }
  });
});
