/**
 * Executable invariants.
 *
 * WHY: CLAUDE.md states rules in prose, and prose does not survive fifty
 *      commits. These tests are the cheapest thing in phase 0 and the reason
 *      the rules stay true. They need no database, network, or API key.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { describe, expect, it } from 'vitest';
import { STAGE_MODELS } from '../../src/llm/models';
import { OWNED_BY } from '../../src/ui/tabs';
import {
  ARCHETYPES,
  EVALUATOR_EMAIL,
  EVALUATOR_WEEKLY_BUDGET_USD,
} from '../../src/seed/archetypes';

const ROOT = join(__dirname, '..', '..');
const SEARCH_DIRS = ['src', 'app', 'scripts', 'tests'];
const SKIP_DIRS = new Set(['node_modules', '.next', '.git', 'dist']);

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.has(entry)) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (/\.(ts|tsx)$/.test(entry)) out.push(full);
  }
  return out;
}

// WHY: this file names the very strings it searches for, so it must exclude
//       itself or it always fails. This is the only exemption, and it is here
//       rather than in a list of allowed paths so it cannot quietly grow.
const SELF = 'tests/unit/invariants.test.ts';

// Generated by `supabase gen types`, not hand-written. It legitimately contains
// the llm_calls column names, openrouter_id among them. Also ignored by ESLint
// and Prettier for the same reason.
const GENERATED = 'src/db/types.ts';

function sourceFiles(): { path: string; rel: string; text: string }[] {
  return SEARCH_DIRS.flatMap((dir) => {
    try {
      return walk(join(ROOT, dir));
    } catch {
      return [];
    }
  })
    .map((path) => ({
      path,
      rel: relative(ROOT, path).split(sep).join('/'),
      text: readFileSync(path, 'utf8'),
    }))
    .filter((f) => f.rel !== SELF && f.rel !== GENERATED);
}

describe('CLAUDE.md #11 — untrusted text never reaches the instruction channel', () => {
  /*
   * ADR 0005 §1. This is the layer that is a guarantee rather than a
   * mitigation, and it was previously only an AI-NOTE on a database column —
   * which is exactly why it needed to become a test. Nothing failed if someone
   * ignored the comment.
   */
  it('builds no system prompt by interpolation or concatenation', () => {
    // A `system:` property whose value contains ${...} or a + is a per-call
    // string reaching the instruction channel. Static constants are fine.
    const offenders = sourceFiles().flatMap((f) =>
      f.text
        .split('\n')
        .map((line, i) => ({ line, n: i + 1 }))
        .filter(({ line }) => /\bsystem:\s*[^,\n]*(?:\$\{|\s\+\s)/.test(line))
        .map(({ n }) => `${f.rel}:${n}`)
    );

    expect(offenders, 'pass per-call text in messages, never in system — ADR 0005 §1').toEqual([]);
  });

  it('applies the safety preamble inside the gateway, not at call sites', () => {
    // If this moves to call sites, a new stage can forget it — ADR 0005 §3.
    const gateway = sourceFiles().find((f) => f.rel === 'src/llm/gateway.ts');
    expect(gateway?.text).toContain('SAFETY_PREAMBLE');
  });

  it('scans every completion before returning it, and scans what it returns', () => {
    /*
     * FOUND IN REVIEW: this asserted only `toContain('scanOutput')`, which
     * passes with BOTH scans deleted — the word survives in the comments. It is
     * still a substring grep, which is all this file can do, but it now names
     * the two calls and the word that has to be next to them.
     */
    const gateway = sourceFiles().find((f) => f.rel === 'src/llm/gateway.ts');
    expect(gateway?.text).toContain('scanOutput(content)');
    // The parsed value's leaves — ADR 0005's 2026-09-12 amendment. A document
    // scan is not enough; see `scanValue` and its tests for why.
    expect(gateway?.text).toContain('scanValue(validation.value)');
  });
});

describe('CLAUDE.md #2 — all LLM calls go through the gateway', () => {
  // WHY: duplicated from the ESLint rule on purpose. Lint can be silenced with
  //      an inline disable comment; this cannot.
  const isGateway = (rel: string) => rel.startsWith('src/llm/');

  it('names OpenRouter nowhere outside src/llm/', () => {
    const offenders = sourceFiles()
      .filter((f) => !isGateway(f.rel))
      .filter((f) => /openrouter/i.test(f.text))
      .map((f) => f.rel);

    expect(offenders, 'reach OpenRouter through callLLM() instead').toEqual([]);
  });

  it('reads the API key nowhere outside src/llm/', () => {
    const offenders = sourceFiles()
      .filter((f) => !isGateway(f.rel))
      .filter((f) => f.text.includes('OPENROUTER_API_KEY'))
      .map((f) => f.rel);

    expect(offenders).toEqual([]);
  });

  it('exports exactly the names it lists', () => {
    /*
     * Two call paths since ADR 0025 — `callLLM` for text, `callSpeech` for a
     * coach's voice — and one factory. Every exported name is pinned, however
     * it is declared: a function, class (abstract too), const, let, var, enum,
     * namespace, module, type or interface. So a new export of any of those —
     * an `export async function speak()` that skipped the budget gate — has to
     * be added here on purpose. Re-exports and default exports are refused
     * outright, because a name list cannot see through them.
     *
     * FOUND IN REVIEW, three times: this asserted only that callLLM existed,
     * then matched `export async function` only, then only names beginning
     * `call`.
     */
    const gateway = readFileSync(join(ROOT, 'src', 'llm', 'gateway.ts'), 'utf8');
    expect(gateway, 'a re-export or default export hides what the gateway exposes').not.toMatch(
      /export\s*(?:\{|\*|default\b)/
    );
    const exported = [
      ...gateway.matchAll(
        /export\s+(?:declare\s+)?(?:abstract\s+)?(?:async\s+)?(?:function\s*\*?\s*|const\s+|let\s+|var\s+|class\s+|enum\s+|namespace\s+|module\s+|type\s+|interface\s+)(\w+)/g
      ),
    ].map((m) => m[1]);
    expect(exported.sort()).toEqual(['callLLM', 'callSpeech', 'createGatewayDeps']);
  });
});

describe('CLAUDE.md #10 — the service role key never appears in application code', () => {
  it('is absent from src/ and app/', () => {
    // Scripts and tests may use it for fixture setup; a request path may not.
    const offenders = sourceFiles()
      .filter((f) => f.rel.startsWith('src/') || f.rel.startsWith('app/'))
      .filter((f) => /SERVICE_ROLE|service_role/.test(f.text))
      .map((f) => f.rel);

    expect(offenders).toEqual([]);
  });
});

describe('PLAN.md phase 2 — the critic runs on a different model from the planner', () => {
  it('gives the planner and critic different primary models', () => {
    // WHY: a critic sharing the planner's weights shares its blind spots, and
    //      the safety loop degrades into agreement.
    expect(STAGE_MODELS.planner[0]).not.toBe(STAGE_MODELS.critic[0]);
  });

  it('gives the planner and critic different model families', () => {
    const family = (slug: string) => slug.split('/')[0];
    expect(family(STAGE_MODELS.planner[0]!)).not.toBe(family(STAGE_MODELS.critic[0]!));
  });

  it('gives every stage at least one model', () => {
    for (const [stage, models] of Object.entries(STAGE_MODELS)) {
      expect(models.length, `${stage} has no model configured`).toBeGreaterThan(0);
    }
  });
});

describe('a route a tab owns is reachable from somewhere', () => {
  /*
   * WHY: `/settings` is not in the tab bar — five tabs is the budget ADR 0012
   * set — so the cog on Profile is its ONLY entry point. Deleting that link
   * orphans a whole page and breaks no build, fails no type check, and renders
   * perfectly everywhere else.
   *
   * `src/ui/tabs.test.ts` asserts which tab lights up for the route. That is a
   * different claim from "you can get there", which is this one.
   */
  it('links every OWNED_BY route from a page under app/', () => {
    const pages = sourceFiles().filter((f) => f.rel.startsWith('app/'));

    const orphaned = Object.keys(OWNED_BY).filter(
      (route) => !pages.some((f) => f.text.includes(`href="${route}"`))
    );

    expect(
      orphaned,
      'a tab owns these routes and nothing links to them — they are unreachable'
    ).toEqual([]);
  });
});

describe('the popover clamp is wired end to end', () => {
  /*
   * WHY a source scan rather than a behaviour test: ADR 0022 rejects the
   * modifier-class alternative because "nothing fails when someone forgets it",
   * and review pointed out the shipped fix had the same property — delete the
   * `margin-left` from globals.css, or the reveal handlers from FieldHint, and
   * every check still passed while the page silently scrolled sideways again.
   *
   * `src/ui/hint-position.test.ts` proves the arithmetic. This proves the two
   * ends are still connected, which is the half that was easy to break.
   *
   * AI-NOTE: if the shift ever stops being a CSS custom property, this is what
   *          tells you to update it — do not delete it, re-point it.
   */
  const css = () => readFileSync(join(ROOT, 'app', 'globals.css'), 'utf8');

  it('has globals.css consume the property FieldHint writes', () => {
    expect(css(), '--hint-shift is written but never read').toContain(
      'margin-left: var(--hint-shift'
    );
  });

  it('keeps the hover reveal behind a pointer query', () => {
    /*
     * A touch "hover" is applied after the pointerenter that would measure the
     * bubble, so an unguarded `:hover` reveal can show an unpositioned one on
     * the phone the ADR is about.
     */
    const text = css();
    const hoverReveal = text.indexOf('.hint:hover .hint-bubble');
    expect(hoverReveal, '.hint:hover reveal not found — was it renamed?').toBeGreaterThan(0);

    const guard = text.lastIndexOf('@media (hover: hover)', hoverReveal);
    expect(guard, 'the :hover reveal is not inside a `hover: hover` query').toBeGreaterThan(0);
    expect(text.slice(guard, hoverReveal)).not.toContain('}\n}');
  });

  it('measures on every route that reveals the bubble', () => {
    const component = readFileSync(join(ROOT, 'src', 'ui', 'FieldHint.tsx'), 'utf8');
    for (const handler of ['onPointerEnter', 'onPointerLeave', 'onFocus', 'onBlur']) {
      expect(component, `${handler} is gone — a reveal path lost its measurement`).toContain(
        handler
      );
    }
  });
});

describe('ADR 0028 — what a failed action may tell the user, and what it may log', () => {
  /*
   * WHICH errors are the user's business is a judgement and is not lintable —
   * the ADR says so, and `src/llm/failure.ts` is where that judgement lives,
   * tested there.
   *
   * The leak SHAPE is lintable, and that is what these two assert. Both patterns
   * had shipped and been found by review six times between them, each time at
   * whichever site a reviewer happened to be reading. A grep would have found
   * the seventh before a person did.
   */
  it('logs no error OBJECT, only a name and a bounded message', () => {
    /*
     * `console.error('…', cause)` prints an Error's own enumerable properties
     * after the stack. `LlmCallFailedError` declares `attempts: LlmCallInsert[]`,
     * and every one of those rows carries `user_id` — so this wrote the user's
     * auth UUID into the server log up to three times per failure, plus the
     * upstream body.
     */
    const offenders = sourceFiles()
      .filter((f) => f.rel.startsWith('app/') || f.rel.startsWith('src/'))
      .flatMap((f) =>
        f.text
          .split('\n')
          .map((line, i) => ({ line, n: i + 1 }))
          .filter(({ line }) => /console\.error\([^)]*,\s*(cause|error|err|e)\s*\)/.test(line))
          .map(({ n }) => `${f.rel}:${n}`)
      );

    expect(offenders, 'log logLine(cause), never the object — ADR 0028').toEqual([]);
  });
});

describe('the voice switch is wired end to end', () => {
  /*
   * WHY a source scan, the same reasoning `the popover clamp` gives above: the
   * painted switch is a sibling selector over a clipped input, and nothing fails
   * when somebody reorders the two spans. The ON state silently stops painting,
   * every check stays green, and the control still toggles — so the bug is
   * invisible to the type system, the linter and the test suite at once.
   *
   * FOUND IN REVIEW of PR #62, which shipped the coupling with no test.
   *
   * AI-NOTE: if the switch ever stops being an adjacent-sibling paint, this is
   *          what tells you to update it — re-point it rather than delete it.
   */
  const css = () => readFileSync(join(ROOT, 'app', 'globals.css'), 'utf8');
  /*
   * RE-POINTED in rework PR 6, as the AI-NOTE above asks. The markup moved from
   * `SessionCoach.tsx` into `src/ui/SpeakSwitch.tsx` when the Coach tab's chat
   * became the second surface to render it — so there is ONE switch to scan now,
   * which both surfaces import, rather than two copies either of which could
   * drift. The test failed on the move, which is the guard doing its job.
   */
  const component = () => readFileSync(join(ROOT, 'src', 'ui', 'SpeakSwitch.tsx'), 'utf8');

  it('paints the checked state from the input that carries it', () => {
    expect(css(), 'the switch no longer paints its ON state').toContain('input:checked + .track');
  });

  it('keeps the input immediately before the track it paints', () => {
    /*
     * `+` is adjacent-sibling, so an element between the two breaks it. JSX
     * comments emit no DOM node and CSS ignores text nodes, so what matters is
     * that no ELEMENT is introduced between them.
     */
    const text = component();
    const role = text.indexOf('role="switch"');
    const track = text.indexOf('className="track"');
    expect(role, 'the switch input is gone').toBeGreaterThan(-1);
    expect(track, 'the painted track is gone').toBeGreaterThan(role);

    /*
     * The first version of this matched the whole span with one lazy regex,
     * and a lazy quantifier BACKTRACKS: inserting a `<span />` between the two
     * let `[\s\S]*?` swallow it and the test passed. Slicing is not clever
     * enough to do that.
     */
    const gap = text
      .slice(text.indexOf('/>', role) + 2, track)
      .replace(/\{\/\*[\s\S]*?\*\/\}/g, '')
      .trim();
    expect(gap, 'an element sits between the switch input and its track').toBe('<span');
  });

  it('keeps the cost sentence out of the label and attached as a description', () => {
    // Inside the label it became part of the accessible name and was announced
    // twice, changing on every press — FOUND IN REVIEW.
    //
    // The id is a PROP now, because two surfaces render the switch — on
    // different routes, so they never collide, but each names its own sentence
    // at most once each and must not collide. So what is asserted is that the
    // description and the sentence are wired to the SAME prop.
    const text = component();
    expect(text).toContain('aria-describedby={describedBy}');
    expect(text).toContain('id={describedBy}');

    // And the sentence sits after the label closes, not inside it.
    expect(text.indexOf('id={describedBy}')).toBeGreaterThan(text.indexOf('</label>'));
  });

  it('is the switch both surfaces render, rather than a copy on each', () => {
    // Two copies of this markup would be two places for the adjacent-sibling
    // paint and the description wiring to drift. Both import the one component.
    for (const surface of [
      join(ROOT, 'app', 'history', '[id]', 'SessionCoach.tsx'),
      join(ROOT, 'app', 'coach', 'CoachBox.tsx'),
    ]) {
      const text = readFileSync(surface, 'utf8');
      expect(text, surface).toContain('<SpeakSwitch');
      expect(text, surface).not.toContain('role="switch"');
    }
  });
});

describe('ADR 0009 and ADR 0017 — application code never selects an achievement predicate', () => {
  /*
   * WHY: `achievements_read_visible` grants the ROW, and `predicate` is a column
   * on it — the SQL `evaluate_achievements` runs. A `select('*')` on that table
   * typechecks, renders correctly, and hands every visible badge's SQL to the
   * page. The badge catalogue (PR 7 of rework-3.md) was the
   * first surface to read the table directly; this holds every read after it.
   *
   * WHAT THIS DOES NOT PROMISE, and the title used to: that the predicate never
   * leaves the server. The table grant lets any signed-in session ask the API
   * for that column on a visible row. ADR 0017's amendment says why that is
   * accepted; this test is about what the app itself sends.
   */
  const application = () =>
    sourceFiles()
      .filter((f) => f.rel.startsWith('src/') || f.rel.startsWith('app/'))
      .filter((f) => !/\.test\.tsx?$/.test(f.rel));

  it('reads the table with an explicit column list that omits predicate', () => {
    const reads = application().flatMap((f) =>
      [...f.text.matchAll(/from\(\s*['"`]achievements['"`]\s*\)([\s\S]{0,200})/g)].map((m) => ({
        rel: f.rel,
        after: m[1] ?? '',
      }))
    );

    // Not vacuous: the catalogue's read is one of them.
    expect(reads.length).toBeGreaterThan(0);

    for (const { rel, after } of reads) {
      const list = after.match(/^\s*\.select\(\s*'([^']*)'/);
      expect(
        list,
        `${rel}: an achievements read must name its columns in a literal`
      ).not.toBeNull();
      expect(list![1], rel).not.toMatch(/\*|predicate/);
    }
  });

  it('never embeds the table with a star or the predicate from another read', () => {
    /*
     * FOUND IN REVIEW: the test above sees only `from('achievements')`. An
     * embedded resource — `from('achievement_events').select('unlocked_at,
     * achievements (*)')` — passes it, and that is exactly the shape
     * src/db/gamification.ts had until commit f81e591.
     */
    const embeds = application().flatMap((f) =>
      [...f.text.matchAll(/achievements\s*(?:!\w+\s*)?\(([^)]*)\)/g)]
        // A call like `from('achievements')` is not an embed; its "columns" are a quote.
        .filter((m) => !/^\s*['"`]/.test(m[1] ?? ''))
        .map((m) => ({ rel: f.rel, columns: m[1] ?? '' }))
    );

    for (const { rel, columns } of embeds) {
      expect(columns, `${rel}: an embedded achievements read`).not.toMatch(/\*|predicate/);
    }
  });
});

describe('a badge on Profile opens its own card in the catalogue', () => {
  /*
   * Profile links `/badges#<slug>`; the link only lands if /badges gives each
   * card that id. Two files, one contract, and a renamed prop on either side
   * breaks it with no build error — the shape the wiring tests above exist for.
   */
  const read = (...parts: string[]) => readFileSync(join(ROOT, ...parts), 'utf8');

  it('links each held badge by its slug', () => {
    const profile = read('app', 'profile', 'page.tsx');
    expect(profile).toContain('href={`/badges#${b.slug}`}');
    // And each locked slot, which the Quest Log shelf added.
    expect(profile).toContain('href={`/badges#${badge.slug}`}');
  });

  it('gives every card on /badges its slug as its id', () => {
    const page = read('app', 'badges', 'page.tsx');
    const cards = page.match(/<article\b[^>]*className="card badge-card[^"]*"/g) ?? [];
    expect(cards.length).toBeGreaterThanOrEqual(2);
    for (const card of cards) expect(card).toContain('id={badge.slug}');
  });
});

describe('ADR 0033 §2 — a build fetches no font, and the fonts are the ones recorded', () => {
  /*
   * WHY: the display face is committed in app/fonts/ so that `next build` needs
   * no route to Google Fonts, and no browser is sent there either. A
   * `next/font/google` import, or a stylesheet or link naming Google's font hosts,
   * would bring that back silently — it compiles, it renders.
   */
  const FONT_DIR = join(ROOT, 'app', 'fonts');

  it('names Google Fonts nowhere a build or a browser would reach', () => {
    const candidates = [
      ...walk(join(ROOT, 'src')),
      ...walk(join(ROOT, 'app')),
      ...readdirSync(join(ROOT, 'app'))
        .filter((f) => f.endsWith('.css'))
        .map((f) => join(ROOT, 'app', f)),
      ...['next.config.ts', 'proxy.ts']
        .map((f) => join(ROOT, f))
        .filter((f) => {
          try {
            return statSync(f).isFile();
          } catch {
            return false;
          }
        }),
    ];
    const offenders = candidates
      .map((path) => ({
        rel: relative(ROOT, path).split(sep).join('/'),
        text: readFileSync(path, 'utf8'),
      }))
      .filter((f) => f.rel !== SELF)
      .filter((f) =>
        /from\s+['"]next\/font\/google['"]|fonts\.googleapis\.com|fonts\.gstatic\.com/.test(f.text)
      )
      .map((f) => f.rel);
    expect(offenders).toEqual([]);
  });

  /*
   * The bytes recorded in app/fonts/SOURCE.md — FOUND IN REVIEW: a font diff is
   * "binary file changed", and a truncated download or a Git LFS pointer builds
   * green (next/font/local only logs when it cannot read a file's metrics) and
   * ships headings in the fallback. Replacing a file means changing its row there
   * and its hash here, together.
   */
  const PINNED: Record<string, string> = {
    'bricolage-grotesque-latin.woff2':
      'a79fdb52d4a5c76552452f69202add96e287401fff03d3e8c0e38b4dcb5a99cd',
    'bricolage-grotesque-latin-ext.woff2':
      '776f6dcaf03636cd69a5802c94808cc8896c0a66c8e9ce0fe147231b6ee01957',
    'bricolage-grotesque-vietnamese.woff2':
      'b50a9d90a5264f20d1e45be0b948fe947ddb3644557f1e85ef5d3bd06427c944',
  };

  it('serves exactly the files it pins, each a whole woff2', () => {
    const layout = readFileSync(join(ROOT, 'app', 'layout.tsx'), 'utf8');
    const referenced = [...layout.matchAll(/src:\s*'\.\/fonts\/([^']+)'/g)]
      .map((m) => m[1]!)
      .sort();
    expect(referenced).toEqual(Object.keys(PINNED).sort());

    for (const name of referenced) {
      const bytes = readFileSync(join(FONT_DIR, name));
      expect(bytes.subarray(0, 4).toString('latin1'), name).toBe('wOF2');
      // The header's own length field, at offset 8, is the whole file's.
      expect(bytes.readUInt32BE(8), name).toBe(bytes.length);
      expect(createHash('sha256').update(bytes).digest('hex'), name).toBe(PINNED[name]);
    }
  });

  it('draws the display face from the committed files, then the one fallback', () => {
    const layout = readFileSync(join(ROOT, 'app', 'layout.tsx'), 'utf8');
    // The negative check above passes on a tree it failed to read; this cannot.
    expect(layout).toMatch(/from\s+'next\/font\/local'/);
    // WHY every call: a call without it brings its own metric Arial, which sits
    // before the later faces in --display and draws the glyphs they own.
    // Anchored to code, not the doc comment above the calls, which names both.
    const calls = layout.match(/=\s*localFont\(/g) ?? [];
    const noAdjust = layout.match(/^\s*adjustFontFallback:\s*false,/gm) ?? [];
    expect(calls.length).toBe(Object.keys(PINNED).length);
    expect(noAdjust.length).toBe(calls.length);

    const variables = [...layout.matchAll(/variable:\s*'(--font-display-[a-z-]+)'/g)].map(
      (m) => m[1]!
    );
    expect(variables).toHaveLength(calls.length);
    const css = readFileSync(join(ROOT, 'app', 'globals.css'), 'utf8');
    const display = /--display:([^;]+);/.exec(css)?.[1] ?? '';
    const order = [...variables, "'Bricolage Grotesque Fallback'"].map((name) =>
      display.indexOf(name)
    );
    expect(
      order.every((at) => at >= 0),
      display
    ).toBe(true);
    expect([...order].sort((a, b) => a - b)).toEqual(order);
    expect(css).toMatch(/@font-face\s*\{\s*font-family:\s*'Bricolage Grotesque Fallback'/);
  });

  it('ships the licence and the record of where the files came from', () => {
    const files = readdirSync(FONT_DIR);
    // The SIL Open Font License requires its text to travel with the fonts.
    expect(files).toContain('OFL.txt');
    const licence = readFileSync(join(FONT_DIR, 'OFL.txt'), 'utf8');
    expect(licence).toMatch(/SIL Open Font License/);
    // Condition 2 of the licence: the copyright notice travels too.
    expect(licence).toMatch(/Copyright \d{4} The Bricolage Grotesque Project Authors/);
    const source = readFileSync(join(FONT_DIR, 'SOURCE.md'), 'utf8');
    for (const [name, hash] of Object.entries(PINNED)) {
      expect(source, name).toContain(name);
      expect(source, name).toContain(hash);
    }
  });
});

describe("ADR 0026's 2026-09-13 amendment — one account at a higher ceiling", () => {
  /*
   * WHY a unit test for a database figure: it is written in two places that no
   * one run sees together. The seeder writes it on a fresh stack; a migration
   * wrote it to the hosted row. The db suite checks the seeded row, and only
   * this can tell that the migration and the archetype still agree.
   *
   * AI-NOTE: reverting the amendment removes this block with the constants.
   */
  it('raises the ceiling on exactly one archetype, the one the sign-in page fills in', () => {
    const raised = ARCHETYPES.filter((a) => a.weeklyBudgetUsd !== undefined);
    expect(raised.map((a) => a.email)).toEqual([EVALUATOR_EMAIL]);
    expect(raised[0]!.weeklyBudgetUsd).toBe(EVALUATOR_WEEKLY_BUDGET_USD);

    const page = readFileSync(join(ROOT, 'app', 'sign-in', 'page.tsx'), 'utf8');
    expect(page).toMatch(/defaultValue=\{EVALUATOR_EMAIL\}/);
  });

  it('left the hosted row where the archetype says — the latest migration that sets a ceiling', () => {
    // The LATEST, by filename: a figure changed by a new migration is checked
    // against that one, and a migration that moves the row without the archetype
    // fails here. `:=` in the guard trigger's body is not a SET and is skipped.
    const dir = join(ROOT, 'supabase', 'migrations');
    const setting = readdirSync(dir)
      .filter((f) => f.endsWith('.sql'))
      .sort()
      .map((f) => ({ f, sql: readFileSync(join(dir, f), 'utf8') }))
      .filter(({ sql }) => /\bset\s+llm_weekly_budget_usd\s*=\s*[\d.]+/i.test(sql));
    const latest = setting.at(-1);
    expect(latest, 'no migration sets a ceiling').toBeDefined();

    const figure = /\bset\s+llm_weekly_budget_usd\s*=\s*([\d.]+)/i.exec(latest!.sql)![1];
    expect(Number(figure), latest!.f).toBe(EVALUATOR_WEEKLY_BUDGET_USD);
    expect(latest!.sql, latest!.f).toContain(`'${EVALUATOR_EMAIL}'`);
  });
});

describe('ADR 0034 — a rest day is today, and paid by the award', () => {
  /*
   * WHY a source check: nothing under app/ is in the unit suite, and the two
   * things that make Rest today safe are properties of the action's shape — it
   * takes no form data, so it cannot be handed a date, and the date it writes is
   * the user's own. tests/db/rest-days.test.ts holds the rest in the database.
   */
  const source = () => readFileSync(join(ROOT, 'app', 'workout', 'actions.ts'), 'utf8');
  const fn = (name: string) => {
    const match = new RegExp(
      `(?:export )?async function ${name}\\(([^)]*)\\)[^{]*\\{([\\s\\S]*?)\\n\\}`
    ).exec(source());
    expect(match, `${name} is missing or has changed shape`).not.toBeNull();
    return { params: match![1]!.trim(), body: match![2]! };
  };
  // Comments may name anything; the checks read code.
  const code = (text: string) => text.replace(/\/\*[\s\S]*?\*\/|\/\/.*$/gm, '');

  it('takes nothing from the form, and writes the date it read from the user timezone', () => {
    const { params, body } = fn('logRestDay');
    // CLAUDE.md #9: no date field to forge, and not the server's clock.
    expect(params).toBe('');
    expect(code(body)).toMatch(
      /const today = localDateFor\(user\.timezone\);[\s\S]*insertRestDay\(db, user\.id, today\)/
    );
    expect(code(body)).not.toMatch(/new Date\(/);
  });

  it('writes no ledger row itself — ADR 0009 §1', () => {
    expect(code(fn('payAndLand').body)).toMatch(/awardSessionXp\(db, workoutId\)/);
    expect(code(source())).not.toMatch(/from\(\s*'(xp_events|achievement_events)'/);
  });
});
